# Generated by Django 5.2.5 on 2025-08-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20250820_2052'),
    ]

    operations = [
    ]
