name: CI/CD Pipeline

on:
  push:
    branches: [ CI-CD-Final-Deployment_1 ]
  pull_request:
    branches: [ CI-CD-Final-Deployment_1 ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create static directory
        run: |
          mkdir -p static

      - name: Run all tests
        env:
          SECRET_KEY: test_secret_key_123
          DEBUG: False
        run: |
          python manage.py test --noinput --settings=test_settings --verbosity=2

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SSH_USER }}  # ← ИСПРАВИТЬ ЗДЕСЬ!
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/myapp
          git fetch --all
          git reset --hard origin/${{ github.ref_name }}
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
